# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
states = State.create([
  {
 
    "state":"Alabama",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
 
    "state":"Alaska",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
 
    "state":"Arizona",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
 
    "state":"Arkansas",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
 
    "state":"California",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
 
    "state":"Colorado",
    "count":0,
    "milestotal":0,
    "faretotal":0
   },
  {
 
    "state":"Connecticut",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
 
    "state":"District of Columbia",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
 
    "state":"Delaware",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Florida",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Georgia",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Hawaii",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Idaho",
    "count":0,
    "milestotal":0,
    "faretotal":0,
  },
  {
    "state":"Illinois",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Indiana",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Iowa",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Kansas",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Kentucky",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Louisiana",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Maine",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Maryland",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Massachusetts",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Michigan",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Minnesota",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Mississippi",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Missouri",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Montana",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Nebraska",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Nevada",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"New Hampshire",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"New Jersey",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"New Mexico",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"New York",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"North Carolina",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"North Dakota",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Ohio",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Oklahoma",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Oregon",
    "count":0,
    "milestotal":0,
    "faretotal":0
     },
  {
    "state":"Pennsylvania",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Rhode Island",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"South Carolina",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"South Dakota",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Tennessee",
    "count":0,
    "milestotal":0,
    "faretotal":0
    },
  {
    "state":"Texas",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Utah",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Vermont",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Virginia",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Washington",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"West Virginia",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Wisconsin",
    "count":0,
    "milestotal":0,
    "faretotal":0
  },
  {
    "state":"Wyoming",
    "count":0,
    "milestotal":0,
    "faretotal":0
   }
])